version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: local_user     # Usuario principal de la BD
      POSTGRES_PASSWORD: local_pass  # Contraseña del usuario principal
      POSTGRES_DB: athenaid   # Base de datos inicial
    ports:
      - "5432:5432"            
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
